version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: fiscalio-sat-api
    container_name: ${APP_CONTAINER_NAME:-sat-api-app}
    restart: unless-stopped
    working_dir: /var/www
    ports:
      - "${APP_PORT:-10000}:${PORT:-10000}"
    environment:
      - PORT=${PORT:-10000}
    volumes:
      - ./:/var/www
      - ./secrets:/var/www/secrets
    networks:
      - fiscalio-network

networks:
  fiscalio-network:
    driver: bridge
