version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: fiscalio-sat-api
    container_name: sat-api-app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./:/var/www
      - ./secrets:/var/www/secrets
    networks:
      - fiscalio-network

  nginx:
    image: nginx:alpine
    container_name: sat-api-nginx
    restart: unless-stopped
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www
      - ./nginx/conf.d/:/etc/nginx/conf.d/
    networks:
      - fiscalio-network

networks:
  fiscalio-network:
    driver: bridge
